version: '3'

services:
  backend:
    build:
      context: .
      args:
        - NPM_TOKEN=${GIT_NPM_TOKEN}
    ports:
      - 12311:3000
    networks:
      - default
      - shared
    depends_on:
      - mysql
    env_file:
      - .env.production
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/config/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apple_music
      time_zone: UTC
networks:
  shared:
    driver: bridge
