version: '3'

services:
  backend:
    image: apple-music-server
    restart: always
    networks:
      - default
      - music_net
    depends_on:
      - mysql
    env_file:
      - .env
  mysql:
    container_name: apple-music-db
    image: mysql:8
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/config/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    env_file: .env
networks:
  music_net:
    driver: bridge
